### PR TITLE
Add modify transaction request data

### PR DESCRIPTION
**Pull request by MimmyJau**
### Background
Here's a first-pass at addressing issue #46. Right now, users can't modify transaction data in the pending request screen. 

### Solution
The suggested solution (via the convo in the issues thread) was to add a tiny edit button and a popover component.

### Where your attention / approval / suggestions would be helpful
1. The bulk of the logic for the form is [here](https://github.com/paradigmxyz/rivet/compare/main...MimmyJau:rivet:feat/modify-txn#diff-b4d7d56d867e0499fa8e33d49b5983893a041b9a452fe56a3baa7159084df31cR163-R212) and [here](https://github.com/paradigmxyz/rivet/compare/main...MimmyJau:rivet:feat/modify-txn#diff-b76c36d69e07fb05a87807d3ea62d137fe796d5fc692a031c7cf20b42508dc32R37-R44).
2. Updating the request is done by calling `updatePendingRequest()` [directly](https://github.com/paradigmxyz/rivet/compare/main...MimmyJau:rivet:feat/modify-txn#diff-b4d7d56d867e0499fa8e33d49b5983893a041b9a452fe56a3baa7159084df31cR208) in the `pending-request.tsx` screen, rather than sending a message using `backgroundMessenger` like for [`handleApprove()`](https://github.com/paradigmxyz/rivet/compare/main...MimmyJau:rivet:feat/modify-txn#diff-b4d7d56d867e0499fa8e33d49b5983893a041b9a452fe56a3baa7159084df31cL142-L145) and [`handleReject()`](https://github.com/paradigmxyz/rivet/compare/main...MimmyJau:rivet:feat/modify-txn#diff-b4d7d56d867e0499fa8e33d49b5983893a041b9a452fe56a3baa7159084df31cL149-L152). Given that this update is happening outside the normal "flow" of a transaction, I thought this was okay, but let me know if you disagree or if I'm missing some other context.
3. The edit icon is next to the title of `<LabelledContent />`. For one, I thought this looked nicer. For two, it was challenging putting the edit icon on the same line as the text (especially getting the icon to play nicely with `<Text.Truncated />`).
4. As a result of the above, I added a 9px icon size for `<Button.Symbol />` to match the size of the icon in `<Button.Copy />`.
5. Ideally, I would have kept `<Popover />` and `<Form />` decoupled, but for some reason this was harder to do than it sounds. To illustrate with an example, I couldn't find a way to both submit the form and close the popover in one click without resorting to this design. I took inspiration from how `<Text.Truncated />` was exposed to create a `<Popover.Form />` variant even though we don't have a base `<Popover />` component yet.

### Demo video

https://github.com/paradigmxyz/rivet/assets/45905800/6dd3c7df-a3cb-4248-811f-91c6d8a2343a

PS: This would be my first meaningful PR, so any and all feedback would be appreciated :)

### CODE REVIEW

**Comment by MimmyJau** [comment]
@jxom Hi just wanted to politely follow-up and see if there were any thoughts on improvements or revisions. Happy to take as much time to necessary to make changes.

**Comment by jxom** [comment]
@MimmyJau – will review today!

**Comment by jxom** [comment]
Thanks for the PR! Just polished up some things – mainly, moved the `Popover` component into `screens/pending-request` to avoid too-early abstraction, once we use popovers elsewhere, and have an idea of the abstraction we need, then we can compose!

**Comment by MimmyJau** [comment]
Awesome thank you for reviewing! And agree on avoiding the early abstraction with the `Popover` component.

**Pull request merged**
