### PR TITLE
Add filtering of transactions by account

### LINKED ISSUE #44: Feature: Filter transactions by account
### The Request

The ability to see transactions scoped to an account address.

### Problem

Right now, Rivet displays every transaction across all blocks and accounts on the "Transactions" tab. There is no way to filter transactions by account address.

### Solution

As a user, I would like the ability to filter/scope transactions on the "Transactions" tab by account address.

### PR DESCRIPTION
**Pull request by deependujha**
fixes #44

- Developers can filter transactions on the basis of transaction hash, sender address, receiver address.

- Instead of exact search, filtering is done on the basis, if `debouncedSearchText` is present in the transaction body.

- Inspired from filtering at `EtherScan`.

### Relevant ScreenShots:
Screenshot from 2023-09-20 13-17-35

- Let's filter transactions on the basis of an address (it could be sender or receiver)

Screenshot from 2023-09-20 13-17-21

### CODE REVIEW

**Comment by jxom** [comment]
Will review this tomorrow. :)

**Comment by deependujha** [comment]
Sure sir.

**Comment by deependujha** [comment]
Do I have to do something in order to fix this 1 failing check out of 4 (Pull request / Artifacts / Artifacts (pull_request) Failing after 1m)?

**Comment by jxom** [comment]
Good start! Can we also include historical account transactions too (before the fork)? We can use Etherscan API for this: https://docs.etherscan.io/api-endpoints/accounts#get-a-list-of-normal-transactions-by-address – there is also a `src/constants/etherscan.ts` to map to the correct Etherscan for chain.

**Comment by deependujha** [comment]
Cool, I'm on it. 

I've roughly figured out how it can be accomplished. I'm thinking of creating a new custom hook for fetching transactions `(with react-query)` and then concatanting the response with rest and returning the result.

Is this fine or any suggestions?

**Comment by jxom** [comment]
Yep, that direction sounds fine.

**Comment by deependujha** [comment]
I think, it will be better if we treat this as separate issue/feature. This is so, because, currently `transactions` is being referenced everywhere in the component which is a synchronous function. As soon as we include `async & await`, a lot of things are required to be modified accordingly.

I was trying to do so with minimal changes, but after hours of trying to fix red squiggles without making drastic changes in the source code, I've finally come to realization that it should be handled as a separate issue/feature.

**Pull request merged**
